name: service_worker_example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  service_worker:
    path: '../'

dev_dependencies:
  build_runner: '>=1.6.2'
  build_web_compilers: '>=2.12.0'
  lints:
