name: service_worker_example
author: Istvan Soos <istvan.soos@gmail.com>
description: Service Worker Example

environment:
  sdk: ">=1.19.0 <2.0.0"

dependencies:
  browser: ^0.10.0+2
  service_worker:
    path: '../'
