name: Run CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.dart }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dart: [stable, beta, dev]
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: ${{ matrix.dart }}
      - uses: actions/checkout@v2
      # Install dev_test binaries
      - run: pub global activate dev_test
      # Run common validation test (analyzer, format, test) on your package (and nested packages)
      - run: pub global run dev_test:run_ci
